{
    "name": "TruCalc Branding",
    "version": "19.0.1.7.0",
    "author": "TruCalc",
    "license": "LGPL-3",
    "category": "Hidden",
    "summary": "TruCalc authentication and browser identity",
    "depends": [
        "web",
        "portal",
        "auth_signup",
        "auth_totp_mail",
        "digest",
        "mail_bot",
    ],
    "data": [
        "data/backend_admin_data.xml",
        "data/pwa_config.xml",
        "data/mail_branding_data.xml",
        "data/mailbot_data.xml",
        "views/web_templates.xml",
        "views/backend_admin_views.xml",
        "views/pwa_templates.xml",
        "views/portal_templates.xml",
        "views/mail_templates.xml",
        "views/auth_mail_templates.xml",
        "views/digest_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "trucalc_branding/static/src/scss/branding.scss",
            (
                "after",
                "web/static/src/core/install_scoped_app/install_scoped_app.xml",
                "trucalc_branding/static/src/xml/install_scoped_app.xml",
            ),
            (
                "after",
                "web/static/src/public/error_notifications.js",
                "trucalc_branding/static/src/js/public_error_notifications.js",
            ),
        ],
        "web.assets_backend": [
            "trucalc_branding/static/src/js/title_service.js",
            (
                "after",
                "web/static/src/core/install_scoped_app/install_scoped_app.xml",
                "trucalc_branding/static/src/xml/install_scoped_app.xml",
            ),
            (
                "after",
                "web/static/src/webclient/user_menu/user_menu_items.js",
                "trucalc_branding/static/src/js/user_menu_items.js",
            ),
            (
                "after",
                "web/static/src/core/errors/error_dialogs.js",
                "trucalc_branding/static/src/js/error_dialogs.js",
            ),
            (
                "after",
                "web/static/src/core/errors/error_dialogs.xml",
                "trucalc_branding/static/src/xml/error_dialogs.xml",
            ),
            (
                "after",
                "mail/static/src/core/web/messaging_menu_patch.js",
                "trucalc_branding/static/src/js/messaging_branding.js",
            ),
        ],
        "web.assets_unit_tests": [
            "trucalc_branding/static/src/js/public_error_notifications.js",
            "trucalc_branding/static/tests/title_service.test.js",
            "trucalc_branding/static/tests/backend_branding.test.js",
            "trucalc_branding/static/tests/pwa_branding.test.js",
        ],
    },
    "installable": True,
    "application": False,
}
